### ISSUE TITLE
[FEATURE] partially close dust evolution updater

### ISSUE THREAD

**Issue by ykllo-t** [stammler/dustpy#12]
Hello, dear developer. Excuse me, I'm frustrated when I try to partially close dust evolution updater. 

For example, I set a disk ranges from 1au to 100au with a gap opened by photoevaporation, which will extend during evolution. I want to close dust evolution within this time-varying gap.

Please give me some hints, thanks a lot.

**Comment by stammler** [comment]
Just for clarification: You want to turn off dust growth in a certain region in your simulation and that region can be time dependent?

There is no dust evolution updater, since the dust is integrated. But you could achieve this by modifying the sticking and fragmentation probabilities and setting them to zero in your desired interval.

```python
from dustpy import Simulation
from dustpy import constants as c
from dustpy import std
import numpy as np

r_in = 10. * c.au
r_out = 30. * c.au

sim = Simulation()
sim.initialize()

def p_stick(sim):
    mask = np.logical_and(sim.grid.r>r_in, sim.grid.r<r_out)[:, None, None]
    return np.where(mask, 0., std.dust.p_stick(sim))
sim.dust.p.stick.updater = p_stick

def p_frag(sim):
    mask = np.logical_and(sim.grid.r>r_in, sim.grid.r<r_out)[:, None, None]
    return np.where(mask, 0., std.dust.p_frag(sim))
sim.dust.p.frag.updater = p_frag

sim.update()
sim.run()
```

Above setup would turn off dust growth/fragmentation in a ring between 10 AU and 30 AU, while keeping dust transport as is.
You can then additionally make `r_in` and `r_out` time dependent.

![dustevol_interval](https://github.com/user-attachments/assets/7bbad8fd-bc89-4a19-8043-1902d6233000)

Let me know if that helped.
Btw: there's also the [discussion forum](https://github.com/stammler/dustpy/discussions/categories/q-a) on GitHub for setup related question.

**Comment by ykllo-t** [comment]
Thank you! This answer does solve my doubts, I can also set other dust behaviors trough this way.
